# Generated by Django 2.2 on 2019-08-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('self_edif', 'Let user edit selfopsts'),)},
        ),
    ]
