# Generated by Django 2.2 on 2019-08-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190813_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('self_edif', 'Let user edit selfopsts'), ('can_delete', 'Can delete posts'))},
        ),
    ]
